runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /visual.html
  static_files: static/visual.html
  upload: static/visual.html

- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest